function b = bfunc(T,ddthetamax1)
%BFUNC
%    B = BFUNC(T,DDTHETAMAX1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.


mt1 = [ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1];
mt2 = [3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1];
b = [mt1;mt2];
