function bl = blfunc(T,ddthetamax1)
%BLFUNC
%    BL = BLFUNC(T,DDTHETAMAX1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    26-Nov-2024 09:09:11

mt1 = [ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;ddthetamax1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1];
mt2 = [3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1;3.0./1.0e+1];
bl = [mt1;mt2];
